modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"

[[mods]]
modId = "itemblacklist"
version = "${file.jarVersion}"
displayName = "Item Blacklist"
authors = "pitbox46"
description ="Allows Blacklisting Items on Servers"
credits='''Thank you X_Niter for multiple contributions to this mod'''


[[dependencies.itemblacklist]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.1.0,)"
    ordering = "NONE"
    side = "SERVER"
